import './globals.css'
import type { Metadata } from 'next'
import { Poppins} from 'next/font/google'
import Footer from './components/Footer/footer'
import NavBar from "./components/NavBar/navbar"
import CartProvider from '@/providers/CartProvider'
import { Toaster } from 'react-hot-toast'
const poppins = Poppins({ subsets: ['latin'], weight:['400','700'] })

//seo buraya yazıyoz
export const metadata: Metadata = {
  title: 'Elite Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
          <Toaster toastOptions={{style:{
            background: 'rgb(51 65 85)',
            color: '#fff',
          }}}/>
       <CartProvider>
       <div className='flex flex-col min-h-screen'>  
            <NavBar/>
            <main className='flex-grow '>{children}</main>
            <Footer/>
        </div>
       </CartProvider>
         

        </body>
    </html>
  )
}
